version: '3.7'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pastbin_db
      MYSQL_USER: test
      MYSQL_PASSWORD: yourPassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  pastbin-app:
    image: pastbin-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/pastbin_db
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: yourPassword
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
    ports:
      - "8080:8080"
    depends_on:
      - mariadb

volumes:
  db_data:
