version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: pastbin_postgres
    environment:
      POSTGRES_USER: yourUsername
      POSTGRES_PASSWORD: yourPassword
      POSTGRES_DB: pastbin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: pastbin_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  pastbin:
    build: .
    container_name: pastbin_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pastbin
      SPRING_DATASOURCE_USERNAME: yourUsername
      SPRING_DATASOURCE_PASSWORD: yourPassword
      SPRING_REDIS_HOST: redis
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
